道路ネットワークの構造クラス作成とコリジョンメッシュからの自動生成の仮実装
Synesthesias/PLATEAU-SDK-for-Unity pull request #250
Opened 2024-05-09 10:51 UTC by rennone

﻿## 関連リンク
特になし

## 実装内容

### 道路ネットワークのクラス作成
RoadNetworkフォルダ以下のRoadNetoworkModel/RoadNetworkLane等
ランタイムで使うためのもの、ほかのレーンへの参照はクラスで直接持っている。
https://synesthesias.atlassian.net/wiki/spaces/PS/pages/358810124/LOD1
にあるクラス図に沿っているが、Id -> クラス参照となっていたり、一部まだ使わないもの定義されていなかったりする

### ポリゴンリストからの道路ネットワークの生成処理
RoadNetworkFactory.cs
１ポリゴンを1リンクとして定義, 隣接判定は共有する頂点があるかどうかで判定。
さらに１リンクをセンターラインで二つのレーンに分割しているが、センターラインの生成アルゴリズムは仮

### 道路ネットワークのシリアライズ/でシリアライズ処理
RoadNetwork/Dataフォルダ以下

RoadNetworkModel -> RoadNetworkStorageに対応
それらの相互変換をRoadNetworkSerializerが行う。
変換する際、データ側に以下の属性を指定することで変換元のメンバ/クラスを見ている
RoadNetworkSerializeData : シリアライズ元のクラスして
RoadNetworkSerializeMember : シリアライズ元のクラスのどのメンバを見るかを指定する

## マージ前確認項目
- [ ] Squash and Mergeが選択されていること
- [ ] UI、挙動に変更ある場合、ユーザーマニュアルが更新されていること

## 動作確認
1. 都市情報がインポートされたシーンを用意する. (今回は新宿でテスト)
2. GameObjectを配置し、PLATEAURoadNetworkTesterスクリプトをアタッチする
3. Targetsの項目に、生成対象となるtranを設定する。もしくはTarget Allにチェックを入れると配置されている全tranで構築になる
4. Createボタンを押すと、道路ネットワークが生成されデバッグ表示が行われる
5. 表示オプション (法線表示するか等)はDrawerメンバ以下で指定する
6. Serialize/Deserializeボタンを押すとシリアライズ/デシリアライズされ, Storage変数に代入している

![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/1005968/5fb94c98-2c2f-4f20-9cac-9d3ff62605a1)
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/1005968/83b8e340-cd3e-4fb2-99cc-3efe6cc8ef93)

## その他
もともとは、Storageを保持して、それ以外はすべてハンドル参照にする予定でしたがランタイムで毎回参照するのがきつかったので、シリアライズするデータクラスとランタイムデータクラスを完全分離しています。
今後、ランタイムデータクラスの内部にストレージクラスを持たせて参照する形式に変えるかもしれませんが現状はこれで進めようかと

2024-05-10 09:21 UTC, Ronnel216 commented
プルリクありがとうございます。
私のソースコードの整備と実装して頂いた内容を確認しました。
気になった点と後ほど私の方で修正する予定ものを記載します。

気になった点
1. マテリアルの変更がコミットされている
コミット対象外になる認識でした。
先々週のミーティングで軽く話しただけですがlinoalさんに相談する話だったと思います。
私は忘れていました。

2. RnId or RnID　どちらか?
RnIDで記述する認識でした。
勘違いだったらすみません。

修正予定
1. 古い仕様のハンドルクラスを削除して新規の仕様に合わせる
PointHandle、LineStringsHandle、PrimitiveDataHandleManagerあたりが削除予定です。

2. RnIdの生成処理をStrageクラス以外で呼べないようにする
ID生成を直接に行えるようにすると以下のようなことが出来てしまうため修正します。
ID生成のルールがクラスによって違う。生成されたIDがStorageの構造に紐づけられていない。
おそらく簡易的なファクトリーを提供するか、Storageクラスの生成関数を提供する形になると思います。

3. RnIdの内部データの型を隠す(int型プロパティなど)
ミーティングで話した通りです。

2024-05-10 10:41 UTC, rennone commented
> マテリアルの変更がコミットされている
これroad_network_00にマージするときに間違って上がっていたみたいです！取り消しました。
僕も聞くの忘れてました。

> RnId or RnID　どちらか?
僕の認識もRnIDなのでリネームしてコミットしました。ファイル名もRnID.csにしました。

ついでにRoadNetworkWayのPointsプロパティもコミットしてしまいました。

2024-05-13 06:33 UTC, dazzhe reviewed
PRありがとうございます。
そのままだとコンパイルエラーでこけましたが、自動生成できるところまで手元で動作確認とれました。データ構造については打ち合わせでも話してるので問題ないです！

![スクリーンショット 2024-05-13 150945](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/10482465/bfa8cd5b-41d5-41dc-8a90-276ab3596f64)

概ね動作問題ないですが道路モデル自体が実際の道路と齟齬ある部分とかあるのでそこは手動編集で解消できるようにしていきたいですね。
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/10482465/ae4b9ff2-941c-4bff-ae7b-4653065cc84d)

@Ronnel216 ?
そのままだとusing足りないようでエラー出てたのでコミット漏れなど無いか確認お願いします 🙏 
また、不要なusing句が含まれているので削除お願いします。
![スクリーンショット 2024-05-12 123012](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/10482465/dab28ca7-a1bd-4625-841a-de59642b76c0)

@linoal 
ざっとフォルダ構成とか問題ないか確認お願いします 🙏

2024-05-13 07:10 UTC, linoal requested changes
ビルドの問題さえ直れば、クールな機能とコードだと思います

2024-05-13 07:36 UTC, linoal approved these changes

2024-05-13 07:37 UTC, linoal commented
LGTM

2024-05-13 08:59 UTC, merged