Feature/road network jira 232
Synesthesias/PLATEAU-SDK-for-Unity pull request #307
Opened 2024-09-17 13:12 UTC by rennone

﻿## 関連リンク
https://synesthesias.atlassian.net/browse/PLTSDK3-232

## 実装内容
* RnRoadを線分で二つに分割する機能 
   * RnModelEx.SliceRoadHorizontal
   * RnModelEx.CanSliceRoadHorizontal (実行可能かどうかのチェック関数)

* RnRoadを2つの線分で３分割し間を交差点にする機能 
  * RnModelEx.SliceRoadHorizontalAndConvert2Intersection
  * RnModelEx.CanSliceRoadHorizontalAndConvert2Intersection

## マージ前確認項目
- [ ] Squash and Mergeが選択されていること
- [ ] UI、挙動に変更ある場合、ユーザーマニュアルが更新されていること

## 動作確認
PLATEAUGeoGraphTesterLineStringを使って動作確認できます。
* 道路構造を生成する
* 空のGameObjectをトップレベルに作成しPLATEAUGeoGraphTesterLineStringをアタッチする
  *  子オブジェクトに空のGameObjectを４つ作る
  * 子オブジェクトの位置で線分が惹かれます
  * インスペクタで以下を設定
    * Axis = Xz (Xz平面に線分描画
    * RoadIntersection Testのenable = true, Plane = Xz
  * 1本目と3本目が道路を分割するように子オブジェクトを移動する
  * Exec2でSliceRoadHorizontalAndConvert2Intersectionが実行される
  * 
![image](https://github.com/user-attachments/assets/6c515e05-4432-46ec-ab95-43ff52a710c6)
![image](https://github.com/user-attachments/assets/6e149f80-0047-4948-a959-0be164af6eaf)

2024-09-21 01:15 UTC, Ronnel216 requested changes
ソースコードにコメントしたので修正お願い致します。

2024-09-21 01:15 UTC, Ronnel216 commented on Runtime/RoadNetwork/Structure/RnLane.cs
> +        /// dirのWayを置き換える. 使い方注意
どのような点に気を付ければよいか分からないので
使い方の注意点について追記をお願いします。
SetBorder()のコメントも同様に対応をお願いします。

2024-09-21 01:15 UTC, Ronnel216 commented on Runtime/RoadNetwork/Structure/RnRoad.cs
> +        ///  隣接情報を差し替える(呼び出し注意)
呼び出し注意の理由も追記お願いします。

2024-09-21 01:15 UTC, Ronnel216 commented on Runtime/RoadNetwork/Structure/RnRoad.cs
> +        /// レーンのLineStringと
クラスのコメントにクラスの役割の情報を追記お願いします。

2024-09-21 01:15 UTC, Ronnel216 commented on Runtime/RoadNetwork/Structure/RnLineString.cs
> +        /// 実際に変える好転はself上の点とその時のインデックス(float)
コメントの誤字を修正してください。

2024-09-21 01:22 UTC, Ronnel216 commented
@rennone 
exec2のトグルボタンをクリックするとエラーが発生しました。
調査をお願い致します。
またこちらで確認してほしいことがあれば共有お願い致します。

以下エラー発生時の設定とエラーの情報です。
動作確認手順にexec 2を押した際にエラーが発生しました。
![error](https://github.com/user-attachments/assets/2fa9f22f-e421-4722-ad47-f8f675d79e06)
![hierarchy](https://github.com/user-attachments/assets/afd88797-9086-4b68-947d-e196ea78928e)
![properties](https://github.com/user-attachments/assets/868f5d91-2c34-41b1-a470-6d935b8c972d)
![scene_view](https://github.com/user-attachments/assets/3a89be29-0c7c-4cf1-87be-21033db6ed87)
![warning](https://github.com/user-attachments/assets/7fa58ac9-bac5-449a-9cd5-4e43fd5da048)

2024-09-23 06:55 UTC, rennone commented on Runtime/RoadNetwork/Structure/RnLane.cs
> +        /// dirのWayを置き換える. 使い方注意
理由追記しました。SetBorderにも追記しました

2024-09-23 06:55 UTC, rennone commented on Runtime/RoadNetwork/Structure/RnRoad.cs
> +        ///  隣接情報を差し替える(呼び出し注意)
理由追記しました

2024-09-23 06:55 UTC, rennone commented on Runtime/RoadNetwork/Structure/RnRoad.cs
> +        /// レーンのLineStringと
コメント追記しました。

2024-09-23 06:55 UTC, rennone commented on Runtime/RoadNetwork/Structure/RnLineString.cs
> +        /// 実際に変える好転はself上の点とその時のインデックス(float)
誤字修正しました。

2024-09-23 06:56 UTC, rennone commented
角の道などで境界線(StartEdgeWay)が存在しない歩道に対して分割しようとすると起きるバグでした。nullチェックを入れて修正しました。

2024-09-23 10:32 UTC, Ronnel216 approved these changes

2024-09-23 10:32 UTC, Ronnel216 commented
@rennone 
問題なさそうです。
対応ありがとうございます。

2024-09-23 10:34 UTC, merged